paths:
  static: ''
  uploads: uploads
timezone: America/Phoenix
markdown:
  engine: commonmark
  options: {}
collections_config:
  pages:
    path: ''
    icon: wysiwyg
  app:
    path: app
    icon: api
  components:
    path: components
    icon: comment
  components_ui:
    path: components/ui
    icon: comment
